### ISSUE TITLE
InoPad not functioning properly after plugging in usb

### ISSUE THREAD

**Issue by berkcambaz** [BerranRemzi/ArcadeBundle#13]
Until serial plotter from arduino ide is opened, InoPad does nothing but waits for signal.

**Comment by berkcambaz** [comment]
```c++
//Initialize serial and wait for port to open:
Serial.begin(115200);
while (!Serial) {
     ; // wait for serial port to connect. Needed for native USB
}
```

**Comment by BerranRemzi** [comment]
`while (!Serial) {
     ; // wait for serial port to connect. Needed for native USB
}`
This part of the code should be deleted or replaced with `delay(500)`

**Comment by BerranRemzi** [comment]
The bug is fixed
